# Project information
site_name: finease
# defeine TOC or order of website-
nav:
  - Home: index.md
  - APIReference: APIReference.md

site_author: Dip Patel
site_description: >-
  A small python library for finacial task made easier using python.

# Repository
repo_name: dipdaiict/finease
repo_url: https://github.com/dipdaiict/finease

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime    
  # logo: PyTorch_logo_icon.svg
  
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/dipdaiict
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/dippatel256

extra_javascript:
  - javascripts/mathjax.js
  # - javascripts/tawk.js
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  
  
plugins:
  - search

copyright: |
  &copy; 2024 <a href="https://github.com/dipdaiict"  target="_blank" rel="noopener">Dip Patel</a>