# Note: Uncomment out when you have some content to test:

name: Python application

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'  
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'  

permissions:
  contents: read

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] 
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v3

    # Step: Set up Python environment
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    # Step: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest tox tox-gh-actions
        pip install -r requirements.txt
        # Additional dependencies can be installed here

    # Step: Test with tox
    - name: Test with tox
      run: tox